apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: php-fpm
  name: php-fpm
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: php-fpm
    spec:
      containers:
      - env:
        {{ range $key, $value := .Values.environment }}
        - name: {{ $key }}
          value: {{ $value }}
        {{ end }}
        image: {{ .Values.docker.image.fpm }}
        name: php-fpm
        ports:
        - containerPort: 9000
        resources: {}
        readinessProbe:
          tcpSocket:
            port: 9000
          initialDelaySeconds: 5
          periodSeconds: 10
      restartPolicy: Always
status: {}
