apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    co.elastic.logs/module: jenkins
    co.elastic.metrics/module: jenkins
    kompose.cmd: kompose convert -c
    kompose.version: 1.18.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: jenkins
  name: jenkins
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: jenkins
    spec:
      containers:
      - env:
        - name: JAVA_OPTS
          value: -Djenkins.install.runSetupWizard=false
        image: jenkins:alpine
        name: jenkins
        ports:
        - containerPort: 8080
        resources: {}
      restartPolicy: Always
status: {}
