apiVersion: v1
kind: Service
metadata:
  annotations:
    co.elastic.logs/module: jenkins
    co.elastic.metrics/module: jenkins
    kompose.cmd: kompose convert -c
    kompose.version: 1.18.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: jenkins
  name: jenkins
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  selector:
    io.kompose.service: jenkins
status:
  loadBalancer: {}
