apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c
    kompose.version: 1.18.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: postgres
  name: postgres
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: postgres
    spec:
      containers:
      - env:
        - name: POSTGRES_DB
          value: {{ .Values.DB_NAME }}
        - name: POSTGRES_PASSWORD
          value: {{ .Values.DB_PASS }}
        - name: POSTGRES_USER
          value: {{ .Values.DB_USER }}
        image: postgres:9.6
        name: postgres
        ports:
        - containerPort: 5432
        resources: {}
      restartPolicy: Always
status: {}
