apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: php-fpm-pv-claim-uploads
  labels:
    app.service: php-fpm
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
