apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: console
  name: console
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: console
    spec:
      containers:
      - env:
        - name: APP_HOST
          value: {{ .Values.APP_HOST }}
        - name: APP_NAME
          value: {{ .Values.APP_NAME }}
        - name: DB_HOST
          value: {{ .Values.DB_HOST }}
        - name: DB_NAME
          value: {{ .Values.DB_NAME }}
        - name: DB_PASS
          value: {{ .Values.DB_PASS }}
        - name: DB_ROOT_PASS
          value: {{ .Values.DB_ROOT_PASS }}
        - name: DB_USER
          value: {{ .Values.DB_USER }}
        - name: HOST_OS_FAMILY
          value: {{ .Values.HOST_OS_FAMILY }}
        - name: MAGENTO_CRYPT_KEY
          value: {{ .Values.MAGENTO_CRYPT_KEY }}
        image: {{ .Values.DOCKER_IMAGE_CONSOLE }}
        name: console
        resources: {}
        readinessProbe:
          exec:
            command:
            - app
            - state
          initialDelaySeconds: 20
          periodSeconds: 10
      restartPolicy: Always
status: {}
