apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: console
  name: console
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: console
    spec:
      containers:
      - env:
        {{ range $key, $value := .Values.environment }}
        - name: {{ $key }}
          value: {{ $value }}
        {{ end }}
        image: {{ .Values.docker.image.console }}
        name: console
        resources: {}
        readinessProbe:
          exec:
            command:
            - app
            - state
          initialDelaySeconds: 20
          periodSeconds: 10
      restartPolicy: Always
status: {}
